# Pushes the contents of the repo to the Codeberg mirror
name: Mirror to Disroot
on: push
jobs:
  disroot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@git.disroot.org:Freakybob/ie6.freakybob.site
          ssh_private_key: ${{ secrets.CODEBERG_SSH }}
